# Generated by Django 5.2.5 on 2025-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='insignia',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='logo_institucion',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
