# Generated by Django 5.2.5 on 2025-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portafolio', '0002_curso_insignia_curso_logo_institucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='cursos/')),
                ('link_github', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
